version: '3.1'

services:
  flask:
    build: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: bash -c "ls /code && "

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/alar_studios_test/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: